# Recovery of cryopreserved cells 

## Instruments

- Biosafety cabinet
- Water bath
- Centrifuge (130 rcf, for 15 mL centrifuge tubes)
- Incubator (37°C, 5% CO~2~)
- Microscope
- Pipettes, etc.

## Materials

- Cryopreserved cells
- Complete growth media
- Cell culture flasks or wells
- 15 mL centrifuge tube
- 70% ethanol, etc.

## Steps

1. Set-up the biosafety cabinet (BSC), water bath to **37°C**, and incubator to **37°C with 5% CO~2~**.
    - Pre-warm the growth media in the water bath

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_BSC`

`r COMMON_RETRIEVE_WARNING_WATER_BATH`

`r COMMON_RETRIEVE_WARNING_INCUBATOR`

:::

2. For each vial of cryopreserved cells, prepare a 15 mL centrifuge tube containing **9 mL** of pre-warmed (to 37°C) growth media.

3. Retrieve the cryopreserved cells, at most two vials at a time. 
   Warm them in the water bath until only a small piece of ice remains, then transfer into the BSC.

4. For each vial, quickly pipette the cell suspension, now completely thawed, into one 15 mL centrifuge tube containing 9 mL of pre-warmed growth media.

5. Centrifuge the cell suspension in the 15 mL centrifuge tube at **24°C and 130 rcf for five minutes** to form a cell pellet.

6. While the centrifuge is spinning, pipette an appropriate volume of fresh pre-warmed growth media into the recipient cell culture flask(s) or well(s).

7. Once the centrifuge is done, dispose of the supernatant by aspirating with a pipette.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_CELL_CULTURE_WASTE`

:::

8. Resuspend the cell pellet with fresh pre-warmed growth media, and dispense into the 6-well plate or cell culture flask(s).

::: {.rmdnote}

`r COMMON_RETRIEVE_NOTE_RESUSPENSION`

:::

9. Inspect the flask(s) under a microscope.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_MICROSCOPE`

:::

10. Gently mix the culture flask(s) and place into the incubator.

## Notes

- Some growth media or growth media components tend to settle in a concentration gradient when left undisturbed; for these liquids, mix by pipetting to eliminate concentration gradients
- When pipetting into cell culture flasks, aspirate 1 mL more than you intend to dispense; this avoids the formation of air bubbles in the culture flask, which may be detrimental to cell growth
- Cell culture flask(s) should be labelled with the name of the cell line, passage number, your name, and the current date
- When mixing cells within a cell culture flask, use vertical up-down and left-right motions; circular motions may gather cells to the flask's center

## Version

This is version ``r COMMON_GET_GIT_COMMIT()``, rendered on `r Sys.Date()`.
