# Thawing/resuscitation of frozen cells 

## Instruments

- Biosafety cabinet
- Water bath
- Centrifuge
- Incubator
- Microscope
- Serological pipette and stripettes
- Pipettes and pipette tips
- Cell culture flasks and centrifuge tubes

## Materials

- Frozen cells
- Growth media, as appropriate for the cell line
- 70% ethanol

## Steps

1. Set-up the biosafety cabeniet (BSC), water bath to 37°C, and incubator to an appropriate temperature and CO~2~ for the cell line.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_BSC`

`r COMMON_RETRIEVE_WARNING_WATER_BATH`

`r COMMON_RETRIEVE_WARNING_INCUBATOR`

:::

2. Prepare the growth media, and keep warm in the water bath.
    - If using fetal bovine serum, mix by pipetting to eliminate any potential concentration gradients

3. Pipette 1ml short of the recommended volume into the cell culture flask(s).
    - Cell culture flask(s) should be labelled with the name of the cell line, passage number, your name, and the current date
    - The recommended amount may vary across cell lines; for MDA-MB-231, for example, a T25 flask should hold 5ml of fresh media while T75 flasks should hold 12ml of fresh media
    - When pipetting, aspirate 1ml more than you intend to dispense; this avoids the formation of air bubbles in the culture flask, which is detrimental to cell growth
    - The reserved 1ml will be used to resuspend the cell pellet later

4. Retrieve the frozen cells. 
   Warm them in the water bath until only a small piece of ice remains.
    - All the steps hereafter until the cells are placed into the culture flask(s) must be done quickly to minimize cell stress

5. Resuspend the frozen cells with 1ml of the fresh pre-warmed growth media and pipette into a centrifuge tube.

6. Centrifuge the resuspended cells at 24°C and 130rcf for five minutes to form a cell pellet.

7. Dispose of the supernatant by aspirating with a pipette.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_CELL_CULTURE_WASTE`

:::

8. Resuspend the cell pellet with 1ml of fresh media, and deposit into the cell culture flask(s).

9. Inspect the confluency of flask(s) under microscope.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_MICROSCOPE`

:::

10. Gently mix the culture flask(s) and place into the incubator.
    - Mix with vertical up-down and left-right motions; avoid circular motions as those tend to gather cells into the center of the flask

## Version

This is version ``r COMMON_GET_GIT_COMMIT()``, rendered on `r Sys.Date()`.
