# Subculturing

## Instruments

- Biosafety cabinet
- Water bath
- Incubator (37°C, 5% CO~2~)
- Microscope
- Pipettes, etc.

## Materials

- Cells
- Complete growth media
- Phosphate-buffered saline buffer (PBS)
- Trypsin solution
- Cell culture flasks or wells
- 70% ethanol, etc.

## Steps

1. Set-up the biosafety cabinet (BSC), water bath to **37°C**, and incubator to **37°C with 5% CO~2~**.
    - Pre-warm the complete growth media and PBS in the water bath

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_BSC`

`r COMMON_RETRIEVE_WARNING_WATER_BATH`

:::

2. Remove cells from the incubator and check for signs of contamination.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_INCUBATOR`

:::

3. Decant or otherwise remove the spent media.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_CELL_CULTURE_WASTE`

:::

4. Wash cells with PBS.
   Repeat the wash for a total of two times.
   On the last wash, aspirate to remove as much liquid as possible.

5. Add trypsin and incubate for up to ten minutes.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_TRYPSIN_STORAGE`

:::
    
6. After incubation, check that cells are detached using a microscope.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_MICROSCOPE`

:::

7. Add fresh medium containing fetal bovine serum (FBS) into the cell culture flask(s) or well(s) containing the trypsinized cell suspension.
   - Gently pipette the cell pellet(s) and suspension(s) using a 1 mL pipette and pipette tip to encourage dissociation.
   Try pipetting 10 to 30 times.
   Aspirate and dispense slowly; and keep the pipette tip away from the tube walls to avoid shearing the celsl.

8. Transfer the cell suspension(s) into new appropriately sized cell culture flask(s) or well(s).
  Top up an appropriate amount of complete growth media, if necessary.

8. Inspect the flask(s) under a microscope.

10. Gently mix the culture flask(s) and place into the incubator.

## Notes

- Some growth media or growth media components tend to settle in a concentration gradient when left undisturbed; for these liquids, mix by pipetting to eliminate concentration gradients
- Avoid introducing air bubbles into growth media, in case they interfere with cell growth
- Cell culture flask(s) should be labelled with the name of the cell line, passage number, your name, and the current date
- When mixing cells within a cell culture flask, use vertical up-down and left-right motions; circular motions may gather cells to the flask's center
- FBS-containing media arrests trypsination because FBS contains trypsin inhibitors

## Version

This is version ``r COMMON_GET_GIT_COMMIT()``, rendered on `r Sys.Date()`.
