# Subculturing/passaging of mammalian cells

## Instruments

- Biosafety cabinet
- Water bath
- Incubator
- Microscope
- Serological pipette and stripettes
- Pipettes and pipette tips
    - Including extended 1ml pipette tips which can cover the length of the cell culture flask(s)
- Cell culture flask(s)

## Materials

- Cells, to be subcultured/passaged
- Growth media containing fetal bovine serum
- Phosphate-buffered saline buffer
- Trypsin solution and FBS
- 70% ethanol

## Steps

1. Set-up the biosafety cabinet (BSC), and warm the water bath to **37°C**.
    - Warm the growth media and phosphate-buffered saline (PBS) buffer
    - Trypsin can be administered cold (4°C) 

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_BSC`

`r COMMON_RETRIEVE_WARNING_WATER_BATH`

:::

2. Remove cells from the incubator and check for signs of contamination.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_INCUBATOR`

:::

3. Decant the spent media.

::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_CELL_CULTURE_WASTE`

:::

4. Wash cells with **(3ml if T25 / 5ml if T75)** PBS and decant.
   Repeat the wash for a total of three times.
   On the last wash, aspirate to remove as much liquid as possible.

5. Add **(1ml if T25 / 2ml if T75)** of trypsin and incubate for up to five minutes.
    
6. While the cells are incubating, pipette **(2ml–4ml if T25 / 6ml–13ml if T75)** of fresh media into new flask(s).

7. After incubation, check that cells are detached using a microscope.

8. Add **(1ml if T25 / 2ml if T75)** of fresh medium containing fetal bovine serum (FBS) into the cell culture flask(s).
   Mix and rinse the base of the cell culture flask by pipetting. 

9. Transfer the cells from the old to new culture flask(s), and place inside the incubator.

## Notes

- Signs of contamination include opaque media visible to the naked eye, or strange debris under the microscope
- Detached cells appear circular and mobile
- Cell culture flask(s) should be labelled with the name of the cell line, passage number, your name, and the current date
- When pipetting fresh media, aspirate more than you intend to dispense to avoid the formation of air bubbles, which can be detrimental to cell growth
- FBS-containing media arrests trypsination because FBS contains trypsin inhibitors

## Version

This is version ``r COMMON_GET_GIT_COMMIT()``, rendered on `r Sys.Date()`.
