# Protein quantification (BCA)

This protocol is adapted from that of the Pierce BCA protein assay kit (ThermoFisher #23225), microplate variation, with 1:20 sample to working solution dilution ratio.

## Instruments

- Microplate
- Microplate reader
- Incubator
- Pipette and pipette tips

## Materials

- RIPA buffer, complete
- Protein samples

## Steps

1. Prepare an appropriate volume of working solution using the expression:
   $$\{2 \times (9 \text{ standards} + x \text{ samples}) \text{ wells}\} \times 200 \text{ μL},$$
   giving allowance for pipetting errors.

2. If not yet prepared, prepare the standards using incomplete RIPA buffer (ThermoFisher #89900) as diluent.
   Set aside 2.5 mL of incomplete RIPA for the standards, since the nine stock solutions require exactly 2.4 mL of diluent.

3. Prepare the same incomplete RIPA buffer (ThermoFisher #89900) as diluent for protein samples.
   Each protein sample requires 18 μL of incomplete RIPA diluent, so the total required volume of incomplete RIPA buffer is:
   $$20 \text{ μL} \times x \text{ samples}.$$

4. Pipette 10 μL of standard solution into each of their assigned microplate wells.

5. Pipette 9 μL of incomplete RIPA buffer into each protein sample's microplate wells.

6. Pipette 1 μL of protein into each protein sample's microplate wells.

7. Pipette 200 μL of working solution into each well.
   Do so in two rounds: the first round for the first replicate of each standard or sample, and then another round for the second replicate.

8. Wrap with foil and incubate at 37°C using the incubator, for 30 minutes.
    - The manufacturer's protocol may ask that the solution be shaken while incubating, but it is okay to omit the shaking
    
::: {.rmdwarning}

`r COMMON_RETRIEVE_WARNING_INCUBATOR`

:::
    
9. Read the plate using a plate reader.
    a. Use the plate reader on level 6, near the media preparation room
    b. Switch on the plate reader via its power switch at the back of the machine
    c. Log into the PC next to the plate reader, and open "Megallan V7.1 Tecam" via the start menu
    d. When the software starts up, specify the device model but leave all other settings to auto-detect
    e. Skip all registration prompts
    f. Use the predefined "BCA 503" method, under the 503 folder
    g. Insert the microplate with the lid removed
    h. Ensure that shaking is an action within the predfined method
    i. Start the plate reader
    j. Remove the microplate once down, and take a photo of the results

10. If there are still spare wells in the microplate, it can be reused.
   - Keep the microplate in the cabinet at the bench assigned for protein work

## Version

This is version ``r COMMON_GET_GIT_COMMIT()``, rendered on `r Sys.Date()`.
